CREATE TABLE IF NOT EXISTS fire_area_canada_usa_unions_{{BUFFER_DISTANCE}} (
    year INTEGER NOT NULL,
    geometry geometry(Geometry,3978),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    PRIMARY KEY ("year", "id")
);


CREATE INDEX IF NOT EXISTS
    idx_fire_area_canada_usa_unions_{{BUFFER_DISTANCE}}_geometry
ON 
    fire_area_canada_usa_unions_{{BUFFER_DISTANCE}}
USING 
    GIST ("geometry");


INSERT INTO 
    fire_area_canada_usa_unions_{{BUFFER_DISTANCE}} (year, geometry)
SELECT 
    {{YEAR}} 
        AS year,
    ST_Union(original.buffer_geometry_{{BUFFER_DISTANCE}}) 
        AS geometry
FROM 
    fire_area_canada_usa{{YEAR}} 
        AS original;